import * as yup from 'yup';
import { Response, Request as ExpressRequest } from 'express';

import { userRegistrationSchema, userVerificationSchema, emailSchema, userUpdateSchema, idSchema } from '../../schemas/validation.schema';
import { UserCreationAttributes } from '../../types/user.type';
import { handleError } from '../../middlewares/error.handler';
import { TypedRequest, ValidationErrorResponse, UserResponseData } from '../../types/type';
import { UserRepository } from '../repositories/user.repository';
import { User } from './user.model';
import { CreationAttributes } from 'sequelize';
import userService from './user.service';


const UserController = {
  
  register: async (req: TypedRequest, res: Response): Promise<Response> => {
    try {
      const validatedData = await userRegistrationSchema.validate(req.body, { 
        abortEarly: false 
      });
      const estate_id = await idSchema.validate(req.query.estate_id, { abortEarly: false });
      
      const { confirm_password, ...userData } = validatedData;
      const userCreationData: UserCreationAttributes = {
        ...userData,
        verified: false,
        estate_id: estate_id,
        role: "resident",
        _creationAttributes: {},
        id: undefined // This will be generated by the database
      };
      const user = await new UserRepository().create(userCreationData);
      
      return res.json(user);
    } catch (error: unknown) {
      if (error instanceof yup.ValidationError) {
        console.log('ERROR DUE TO VALIDATION', error)
        const errors: ValidationErrorResponse[] = error.inner.map(err => ({
          field: err.path || 'unknown',
          message: err.message
        }));
        
        return res.status(400).json({
          status: 'error',
          message: 'Validation failed',
          errors
        });
      }
      const errorMessage = error instanceof Error ? error.message : 'Unknown error occurred';
      return res.status(500).json({
        status: 'error',
        message: 'Internal server error',
        error: errorMessage
      });
    }
  },

  verifyUser: async (req: ExpressRequest, res: Response ): Promise<Response> => {
    try {
      const validatedData = await userVerificationSchema.validate(req.body, { abortEarly: false });
      
      const { email, code } = validatedData;
      // const verificationResult = await verifyUser({ email, code });

      // return res.status(verificationResult.statusCode).json(verificationResult);
    } catch (error: unknown) {
      if (error instanceof yup.ValidationError) {
        return res.status(400).json({
          status: 'error',
          message: 'Validation failed',
          errors: error.errors.map(errorMsg => ({
            message: errorMsg
          }))
        });
      }
      const errorMessage = error instanceof Error ? error.message : 'Unknown error occurred';
      
      return res.status(500).json({
        status: 'error',
        message: 'Internal server error',
        error: errorMessage
      });
    }
  },

  resendCode: async (req: TypedRequest, res: Response): Promise<Response> => {
    try {
      const emailPayload = await emailSchema.validate(req.body, { abortEarly: false });
      
      const resend = await resendCode(emailPayload.email);
      
      return res.status(resend.statusCode).send({ 
        status: 'success', 
        message: 'Verification code resent',
        data: resend.data
      });
    } catch (error) {
      if (error instanceof yup.ValidationError) {
        return res.status(400).send({
          status: 'error',
          errors: error.errors
        });
      }
      
      return res.status(500).send({
        status: 'error',
        message: 'Internal server error',
        details: error instanceof Error ? error.message : error
      });
    }
  },


  getAllUsers: async (req: ExpressRequest, res: Response): Promise<Response> => {
    try {
      const users: UserResponseData = await getAllUsers();
      return res.status(users.statusCode).send({
        status: users.status,
        message: users.message,
        data: users.data
      });
    } catch (error: any) {
      const errorResponse = handleError(error as Error);
      return res.status(errorResponse.statusCode).json(errorResponse.message);
      };
  },

  getOneUser: async (req: ExpressRequest, res: Response): Promise<Response> => {
    try {
      const user = await userService.getUserById(req.params.id);
      return res.status(user.statusCode).send({ 
        status: (user.status), 
        message: (user.message), 
        data: (user.data)
      })
    } catch (error) {
      console.log(error);
      return res.status(500).send({
        error: error
      })
    }
  },

  updateUser: async (req: ExpressRequest, res: Response): Promise<Response> => {
    try {
      const id = req.params.id;
      const validatedData = await userUpdateSchema.validate(req.body, req.params);
      const update = await userService.updateUser( id, validatedData);
      return res.status(update.statusCode).send({ status: (update.status), message: (update.message), data: (update.data)})
    } catch (error) {
      return res.status(500).send({
        error: error
      });
    }
  },

  deleteUser: async (req: ExpressRequest, res: Response): Promise<Response> => {
    try {
      const payload = await idSchema.validate(req.params.id);

      const deleteUserById = await UserRepository.delete(payload);
      return res.status(deleteUserById.statusCode).send({
        status: deleteUserById.status,
        message: deleteUserById.message,
        data: deleteUserById.data
      })
    } catch (error) {
      return res.status(500).send({
        error: error
      });
    }
  }
}

export default UserController;
